### ISSUE TITLE
Duplicate messages and notifications

### ISSUE THREAD

**Issue by RTechSn** [nextcloud/flow_notifications#232]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Add a new "Write to conversation" flow
2. Choose:
- When: File created
- File system tag: is tagged with: SomeTag
- Select some conversation
3. Edit a file tagged with SomeTag, for example a txt file.

### Expected behaviour
One chat message should appear for each file modification

### Actual behaviour
2 chat messages appear at the same time

### Server configuration

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 8.3

**Nextcloud version:** 30.0.2

<details>

<details>
I can provide additional details if needed.
</details>

**Comment by RTechSn** [comment]
"File system tag" is irrelevant, "File name is" triggers duplicate message too.

**Comment by RTechSn** [comment]
"Send a notification" flow generates duplicate notification too.

**Comment by RTechSn** [comment]
I'm pretty sure duplicate message\notification is caused by #243

**Comment by blizzz** [comment]
Let's keep it with https://github.com/nextcloud/server/issues/49732
