### ISSUE TITLE
"File created" triggers when file is modified

### ISSUE THREAD

**Issue by RTechSn** [nextcloud/flow_notifications#243]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Add a new "Write to conversation" or "Notification" flow
2. Choose "File created"
3. Set some options

### Expected behaviour
"File created" should trigger only when a new file is created

### Actual behaviour
"File created" triggers when an existing file is modified. 

### Server configuration

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 8.3

**Nextcloud version:**  30.0.2

### Browser

**Browser name:**  Any

**Comment by RTechSn** [comment]
Apparently it's a server issue, not the app.
https://github.com/nextcloud/server/issues/49732

**Comment by blizzz** [comment]
That's right, let's follow there,
