### ISSUE TITLE
Not action under Workflow

### ISSUE THREAD

**Issue by Oratorian** [nextcloud/flow_notifications#26]
I installed Flow Notification and activated it.

But when i navigate to Workflow the only Flow i can manage is for automaticly convert PDF

The "Send a notification" like in https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png

is not showing up for me.

Is there any other setting i have to do?

Using nextcloud ver. 21.0.2

**Comment by top-logic** [comment]
The notification flow is only available in the personal section, not in the administrative section.
![grafik](https://user-images.githubusercontent.com/70580580/120514473-9d516000-c3cd-11eb-8933-a25b599a89dd.png)

**Comment by Oratorian** [comment]
I dont have the Flow option in the Personal section. 😅
