### ISSUE TITLE
I cannat enable Flow Notifications

### ISSUE THREAD

**Issue by LinkatMT** [nextcloud/flow_notifications#54]
I installed and enabled Flow Notifications on NextCloud, but when I go in Flow page, there is nothing to using Flow Notifications. Can u help me? I just installed NextCloud 24.0 and i didnt customize anything yet.

**Comment by blizzz** [comment]
flow notifications are availble for personal flows only, not system-wide ones.

**Comment by LinkatMT** [comment]
I tought so, then I created a standard user, but I wasnt able anyway to use Flow Notifications, maybe some1 can share me a link with a tutorial, about how to use this feature?

**Comment by blizzz** [comment]
Please discuss in the [forums](https://help.nextcloud.com/).
