### ISSUE TITLE
Notifying on new files in a folder

### ISSUE THREAD

**Issue by thniels** [nextcloud/flow_notifications#56]
Taking a cue from an example elsewhere, I made a workflow action with Automatic Tagging. 

1. I have a folder tagged as "Print".
   1. The Automatic Tagging-flow then reacts on...
      1. File Change
      2. File is tagged "Print" (that is inherited from the folder)
      3. MIME type is not Folder
         1. Tag the file as "Notify"
   2. The Notifications-flow then reacts on...
      1. Tag Assigned
      2. File is tagged "Notify"
         1. Send a notification

The first part works like a charm. Files created in the "Print" folder inherit that tag, as do files in subfolders. Flow then gets triggered and adds the "Notify" tag. So far so good. The problem is that the Notification event never gets triggered.

![image](https://user-images.githubusercontent.com/658227/181736417-28191ef1-2510-4455-bcfa-82ed37ab404f.png)

It doesn't make any difference on which user I add the workflow.

**Comment by thniels** [comment]
For a workaround, I did this...

![image](https://user-images.githubusercontent.com/658227/181748947-7b62d5b5-234a-4949-aacb-e74d74cc89b7.png)

...which basically just notifies me if a file not already tagged as "Notify" changes tag from "Print". I suppose it just shows that the "Tag Assigned" event fires before the tag name is known.

This _does_ work but is not really how I would expect it to.

**Comment by blizzz** [comment]
The upper configuration would assume that the tag is present at the time the assignment happens.

**Comment by blizzz** [comment]
As there is no further feedback since a while I will close this issue.
