### ISSUE TITLE
Question: Notification only for specific folder/action

### ISSUE THREAD

**Issue by pongraczi** [nextcloud/flow_notifications#69]
## Scenario
* A user (**Joe**) got a shared folder (**Cute cat videos**), where the owner of the folder (**Judy**) regularly upload/modify files.
* **Joe** usually annoyed by the email/popup notifications from nextcloud, so, he turned off all notifications like this:  
![Kijelölés_220](https://user-images.githubusercontent.com/5891983/213653919-ee2e5fea-5271-4ac9-bd19-f56050e59741.png)  
* **Joe** (of course) would like to get a notification about the shared folder, when new content uploaded, so, he set up a new Flow-notification with the following filter: ``/Cute cat videos\/.+$/i``   and set his email address: ``joe@example.com``
* **Joe** thinks it will work.
* In reality, seems not.

## Notes
My opinion, the scenario, when a user (Joe) will get email notifications in general + flow-notification email, which redundant, is not really what a user (Joe) wants.  
I guess, when the notification will be sent to 3rd party user, that's could be ok and useful.  
Our users in opposit, usually annoyed by the lot of email notifications and there is no way to filter out the noise and only keep some specific changes.  
I could imagine a workaround, using a dummy/technical/proxy user, where this dummy could get all the notifications and its Flow-notification settings contain the filter and real target user's email address, but it seems a bit overkill.

## Questions
* Is this flow notification supposed to work like this?  
  Only send notification, when the user enabled the email notifications in general for files?
* **How could a user suppress all email notifications about files in general and only enable notifications for specific folders?**

Thanks

**Comment by pongraczi** [comment]
## Additional question
* Is that possible, when a filter matches, all the matching filters after the first one will be ignored?

**Comment by blizzz** [comment]
This app creates a notification via the usual notification system. You should see a popup, and dependent on configuration, get an email reminder.  Flow notifications are a personal setting, too. Only the user setting up this flow will be notified and only of actions by others, not of those yourself.
