### ISSUE TITLE
No notification from groupfolders

### ISSUE THREAD

**Issue by sdegrande** [nextcloud/flow_notifications#71]
I have a 'flow' set to notify when a file with a specific name is edited.
It works well for a file in a shared folder, but no notification is pushed for a file in a group folder.

**Comment by VN1977** [comment]
We have the same problem when notifications in group folders don't work.

**Comment by codeHorse87** [comment]
I can confirm this with NC 25.0.6

**Comment by LittleOldXander** [comment]
is this fixed? cause i dont seem to get the group folder notifications to work on 30.0.5
