### ISSUE TITLE
App is installed but does not show up in Available Flows

### ISSUE THREAD

**Issue by heisian** [nextcloud/flow_notifications#91]
Using NextCloud 28.0.1, the Flow notifications app is installed:
![image](https://github.com/nextcloud/flow_notifications/assets/4141828/95091992-d3e6-4852-baa3-a2eadbff1230)

But it doesn't show up when looking at Available Flows:
![image](https://github.com/nextcloud/flow_notifications/assets/4141828/317382df-bed9-4bb8-8a29-4410d3402cb2)

**Comment by blizzz** [comment]
This app appears in Personal Setting → Flow only. Did you check there?
